name: Deploy to Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -v api/main.go

      - name: Run unit tests
        run: go test -v ./...
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda function
        run: |
          make build
          zip -r lambda.zip bin/thumbnail_previewer_backend

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name thumbnail-previewer-backend \
            --zip-file fileb://lambda.zip